package com.kmbl.InventoryManagementService.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "inventory")
public class Inventory {

    @DynamoDBAttribute
    List<Integer> pincodes;
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;
    @DynamoDBAttribute
    private String sellerId;
    @DynamoDBAttribute
    private String productId;
    @DynamoDBAttribute
    private int quantity;
    @DynamoDBAttribute
    private double price;


}
