package com.kmbl.InventoryManagementService.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;


import java.util.List;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "inventory")
public class Inventory {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    public String getSellerId() {
        return sellerId;
    }

    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    @DynamoDBAttribute(attributeName = "sellerId")
    //@DynamoDBIndexRangeKey(globalSecondaryIndexName = "productIdandsellerId-index",attributeName = "productid")
    private String sellerId;

    @DynamoDBAttribute(attributeName = "productId")
   // @DynamoDBIndexHashKey(globalSecondaryIndexName = "productIdandsellerId-index",attributeName = "sellerid")
    private String productId;

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @DynamoDBAttribute
    private int quantity;

    @DynamoDBAttribute
    private double price;

    @DynamoDBAttribute
    List<Integer> pincodes;

    public int getQuantity()
    {
        return quantity;
    }
}
