package com.kmbl.InventoryManagementService.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;


import java.util.List;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "inventory")
public class Inventory {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "productandseller-index",attributeName = "sellerid")
    private String sellerId;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "productandseller-index",attributeName = "productid")
    private String productId;

    @DynamoDBAttribute
    private int quantity;

    @DynamoDBAttribute
    private double price;

    @DynamoDBAttribute
    List<Integer> pincodes;
}
