package com.kmbl.InventoryManagementService.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "product")
public class Product {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String id;
    @DynamoDBAttribute
    String name;
    @DynamoDBAttribute
    String category;
    @DynamoDBAttribute
    String brand;
}
